version: '3.9'

services:
  vault:
    build:
      context: ..
      dockerfile: vault_compose/vault.Dockerfile
    container_name: vault_container
    environment:
      VAULT_LOCAL_CONFIG: |
        {
          "backend": {
            "file": {
              "path": "/vault/file"
            }
          },
          "listener": [{
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_disable": 1,
              "tls_cert_file": "/vault/config/certs/vault.crt",
              "tls_key_file": "/vault/config/certs/vault.key"
            }
          }],
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h",
          "ui": true
        }
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/file
      - ./vault/config:/vault/config
    command: [ "server" ]
    networks:
      - localhost-network

  nginx:
    build:
      context: ..
      dockerfile: vault_compose/nginx.Dockerfile
    container_name: nginx_vault_container
    restart: always
    ports:
      # Port Vault
      - "8200:8200"
    networks:
      - localhost-network

volumes:
  vault_data:

networks:
  localhost-network:
    external: true

#docker network create localhost-network